"""Hey

Revision ID: 4223dba357af
Revises: 83ad1156e91a
Create Date: 2024-03-07 16:56:49.615688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4223dba357af'
down_revision = '83ad1156e91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
